# Generated by Django 4.2.4 on 2023-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='title',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
