# Generated by Django 4.2.4 on 2023-09-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_alter_weblog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='test',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
