# Generated by Django 4.2.4 on 2023-09-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_remove_weblog_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weblog',
        ),
    ]
