# Generated by Django 4.2.4 on 2023-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weblog', '0010_delete_weblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/weblog')),
                ('title', models.CharField(default=None, max_length=80)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('body', models.TextField(default=None)),
            ],
        ),
    ]
