# Generated by Django 4.2.4 on 2023-09-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_rename_body_weblog_p1_weblog_p2_weblog_p3_weblog_p4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p7',
        ),
    ]
