# Generated by Django 4.2.4 on 2023-09-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0014_remove_weblog_p1'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='p1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p2',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p3',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p4',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p5',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p6',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='weblog',
            name='p7',
            field=models.TextField(default=None),
        ),
    ]
