# Generated by Django 4.2.4 on 2023-09-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0015_weblog_p1_weblog_p2_weblog_p3_weblog_p4_weblog_p5_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weblog',
            old_name='p1',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='weblog',
            name='p7',
        ),
    ]
