# Generated by Django 4.2.4 on 2023-09-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0016_rename_p1_weblog_body_remove_weblog_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
