# Generated by Django 4.2.4 on 2023-09-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0017_weblog_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='view',
        ),
    ]
