# Generated by Django 4.2.4 on 2023-09-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0018_remove_weblog_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
