# Generated by Django 4.2.4 on 2023-09-05 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0019_weblog_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
