# Generated by Django 4.2.4 on 2023-09-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0026_alter_weblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblog',
            name='image',
            field=models.ImageField(upload_to='static/images/weblog'),
        ),
    ]
