# Generated by Django 4.2.4 on 2023-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
