# Generated by Django 4.2.4 on 2023-09-06 14:20

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectreq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
