# Generated by Django 4.2.4 on 2023-09-07 11:49

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectreq', '0003_alter_projectrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
