# Generated by Django 4.2.4 on 2023-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('webname', models.CharField(max_length=80)),
                ('link', models.URLField(max_length=100)),
            ],
        ),
    ]
